version: 2
jobs:
  build:
    
    working_directory: ~/podam

    steps:
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: podam-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/podam-0.0.1-SNAPSHOT.jar

